---
- name: Create deploy user
  user:
    name: "{{ deploy_user }}"
    groups: sudo
    shell: /bin/bash
    create_home: yes
    state: present

- name: Set authorized SSH key for deploy user
  authorized_key:
    user: "{{ deploy_user }}"
    key: "{{ deploy_user_pubkey }}"
    state: present

- name: Allow deploy user to sudo without password
  copy:
    dest: /etc/sudoers.d/{{ deploy_user }}
    content: "{{ deploy_user }} ALL=(ALL) NOPASSWD:ALL\n"
    mode: "0440"
    validate: "visudo -cf %s"
